language: c
compiler:
  - gcc
  - clang
env:
  - 
  - USE_XFT=0
before_install:
  - sudo apt-get install lua5.2 liblua5.2-dev gettext libxft-dev libxinerama-dev libxrandr-dev libreadline-dev lua-posix
  - sudo ln -sf /usr/lib/x86_64-linux-gnu/lua/5.2/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so
script:
  - make
  - make test
